--- # roles/myrepos/tasks/debian.yml

- name: "update apt cache"
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: [ 'packages' ]

- name: "Update apt cache and install myrepo reqirements package"
  become: true
  apt:
    name : '{{ item }}'
    state: 'present'
  with_items:
    - git
    - perl-doc
